owncloud/firstrunwizard

templates/wizard.php

cc @DeepDiver1975 
fixes https://github.com/owncloud/core/issues/13469

adjust year

---

templates/wizard.php

Related #30 
Fix owncloud/core#18657
@jancborchardt @LukasReschke

Fix 30 for enterprise themes

---

templates/wizard.php

Same wording for 9.0 as we use for the new frontpage: https://github.com/owncloud/owncloud.org/pull/776
Please review @karlitschek @jospoortvliet

adjust wording to new website

---

css/firstrunwizard.css

With https://github.com/owncloud/core/pull/20447, the heading styles don’t need to be manually defined here anymore.
Please review @owncloud/designers

use standard heading styles

---

templates/wizard.php

Saves us from updating this each year manually. I can remind this hassle already from last year :wink: 
@jancborchardt @karlitschek

Use current year from server

---

templates/wizard.php

Fixes https://github.com/owncloud/core/issues/22201
@DeepDiver1975 @SergioBertolinSG

Use SVG and proper sizes

---

appinfo/info.xml

Please review @karlitschek @LukasReschke @ryno83 @PhilJung

up max-version, fix wording

---

templates/wizard.php

hardcoded "ownCloud Inc." don't work /cc @felixboehm @butonic

make .footnote themable for EE

---

templates/wizard.php

- Backport of https://github.com/owncloud/firstrunwizard/pull/46
/cc @felixboehm @butonic

[stable8.2] make .footnote themable for EE

---

templates/wizard.php

- Backport of https://github.com/owncloud/firstrunwizard/pull/46
/cc @felixboehm @butonic

[stable9] make .footnote themable for EE

---

templates/wizard.php

- Backport of https://github.com/owncloud/firstrunwizard/pull/46
/cc @felixboehm @cdamken

[stable9.1] make .footnote themable for EE

---

appinfo/app.php

Backport of https://github.com/owncloud/firstrunwizard/pull/52 to stable9.1
@DeepDiver1975 @butonic

[stable9.1] Only display wizard popup in files app

---

.travis.yml

Remove old PHP versions from travis config

---

css/firstrunwizard.css
js/jquery.colorbox.js

Fixes first run wizard in IE11.
Note that the issue itself prevents other JS to run so the file list will appear empty for example.
So this is an important fix !
Please review @jvillafanez @PhilippSchaffrath @DeepDiver1975 
To be backported to 9.1. Other versions not affected.
Fixes https://github.com/owncloud/core/issues/26438

Update colorbox to v1.6.4, fixes IE11

---

.travis.yml
css/firstrunwizard.css
js/jquery.colorbox.js

Backport of https://github.com/owncloud/firstrunwizard/pull/56 to stable9.1.
@davitol another chance to test :smile:

[stable9.1] Update colorbox to v1.6.4, fixes IE11

---

templates/wizard.php

fixes https://github.com/owncloud/firstrunwizard/issues/60
@DeepDiver1975

fix Community version check

---

templates/wizard.php

This is an update to https://github.com/owncloud/firstrunwizard/pull/61
Change: using a defined constant instead of a hard coded text.
@davitol @PVince81

Change constant text to constant reference

---

templates/wizard.php

@davitol found a query for edition which I missed to fix (https://github.com/owncloud/firstrunwizard/pull/62). Now I did a search for ``edition`` over the whole owncloud repositories. Just a view lines above of the last change I found (now the last one) that needed adoption too... 
@PVince81

Query for edition, constant missing

---

.gitignore
CHANGELOG.md
COPYING
Makefile

- Add makefile
- add changelog 
- add COPYING (the source is https://github.com/owncloud/core/blob/master/COPYING )
- update gitignore

Add Makefile, Changelog, AGPL, update gitignore

---

css/firstrunwizard.css
templates/wizard.php

See title and https://github.com/owncloud/core/issues/30914

Fix missing googleplay banner

---

css/firstrunwizard.css
templates/wizard.php

Backporting https://github.com/owncloud/firstrunwizard/pull/75

[stable10] fix missing banner

---

js/firstrunwizard.js
js/jquery.colorbox.js

Closes https://github.com/owncloud/firstrunwizard/issues/78
Checkout the core to https://github.com/owncloud/core/tree/jquery-2-migration and run `make` before testing

Make the app compatible with jQuery 1.9+

---

README.md

which I forgot when moving CI  from Travis to drone.

Adjust build status badge for drone

---

appinfo/info.xml
lib/Command/ResetAll.php
lib/config.php
tests/lib/configtest.php

Backport #83 
I noticed this because I was backporting recent CI changes.

[stable10] Add occ command to reset for all users

---

composer.lock
phpunit.xml
tests/lib/configtest.php
tests/lib/utiltest.php

1) Bump composer-bin-plugin v1.3.0
2)  Adjust PHPUnit Framework namespace for PHPUnit6 
3) enable failOnRisky failOnWarning

Phpunit 5 6

---

.drone.yml
composer.json
composer.lock
phpunit.xml
tests/lib/configtest.php
tests/lib/utiltest.php

[stable10] drop php 5.6

---

.drone.yml

This test guarantee that the ```firstrunwizard``` app runs correctly against the last released core version.
Part of https://github.com/owncloud/QA/issues/611

firstrunwizard test against latest tarball

---

.drone.starlark
.drone.yml
tests/acceptance/features/webUIFirstrunwizard/firstrunwizard.feature

1) Initial drone starlark config
2) Skip one acceptance test scenario on firefox. It gives:
```
When the user requests to show firstrunwizard popup in settings page           # WebUIFirstrunwizardContext::requestToShowFirstRunWizardPopupInSettingsPage()
WebDriver\Exception\MoveTargetOutOfBounds: (364.5, 904.8583679199219) is out of bounds of viewport width (1360) and height (899)
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'
System info: host: 'a28388997375', ip: '172.22.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-54-generic', java.version: '1.8.0_151'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: false, browserName: firefox, browserVersion: 58.0, javascriptEnabled: true, …
```

Initial drone starlark

---

.drone.starlark
.drone.yml
composer.json
composer.lock
phpunit.xml
vendor-bin/behat/composer.json

Similar to https://github.com/owncloud/configreport/pull/121
Note: there were no phpunit setUp or tearDown functions to fix

Adjust tests

---

vendor-bin/behat/composer.json

Needed because of owncloud/core#36999

[Tests-Only] Update guzzle for testing to 6.5

---

.drone.star
lib/config.php
phpstan.neon
vendor-bin/phpstan/composer.json

Related - owncloud/QA#642
Update phpstan to 0.12

[Tests-Only] Update phpstan to latest version

---

.drone.star
.phan/config.php
vendor-bin/phan/composer.json

Part of https://github.com/owncloud/QA/issues/643

[Tests-Only] Bump phan 2.7 & Run phan in CI

---

.gitignore
.phpunit.result.cache
vendor-bin/behat/composer.json

Part of https://github.com/owncloud/QA/issues/647

[Tests-Only] Implement PHPunit v8

---

tests/acceptance/features/webUIFirstrunwizard/firstrunwizard.feature
tests/acceptance/features/webUIFirstrunwizard/headingMessage.feature
tests/acceptance/features/webUIFirstrunwizard/resetAll.feature

Similar to what was done in core recently.

Use realistic usernames

---

tests/acceptance/features/bootstrap/WebUIFirstrunwizardContext.php
tests/acceptance/features/bootstrap/bootstrap.php
tests/acceptance/features/lib/FirstRunWizardPage.php
tests/acceptance/features/lib/PersonalGeneralSettingsPageFirstRunWizard.php

Related https://github.com/owncloud/QA/issues/694
- add strict type checking on acceptace test code
**note** this PR was generated by a automated script

[Tests-Only] enforce strict type checking in acceptace tests code

---

phpunit.xml

This PR moves unit tests into tests/unit folder. And also tidy up the `phpunit.xml` to make standard format for all oc-apps as much as possible.
- Part of https://github.com/owncloud/impersonate/issues/198

[tests-only][full-ci]Tidy up the phpunit xml file for firstrunwizard app

---

.drone.star
.gitignore

it is better to use directory references from the dir var, rather than using the hard-coded values in every use case.
- https://github.com/owncloud/QA/issues/734#issue-1173320353
- CI

[tests-only][full-ci]Use directory references from global dir variable in drone.star file

---

tests/acceptance/features/webUIFirstrunwizard/firstrunwizard.feature
tests/acceptance/features/webUIFirstrunwizard/headingMessage.feature
tests/acceptance/features/webUIFirstrunwizard/resetAll.feature

Interspacing between two scenarios is made consistent as documented https://github.com/owncloud/docs-server/pull/697/files#diff-12a0f404a5bbbda65e50018a487cd725797106d670f4308b921d2081dc4b3516R1129-R1154:~:text=more%20relevant%20discussion.-,%3D%3D%3D%3D%20Inter%2Dscenario%20spacings,%2D%2D%2D%2D,-Commenting%20on%20lines
- Part of https://github.com/owncloud/QA/issues/769
- :robot:

[full-ci] [tests-only] Refactored inter scenarios space

---

.drone.star
composer.json
composer.lock
lib/config.php
tests/acceptance/features/bootstrap/WebUIFirstrunwizardContext.php
tests/unit/lib/configTest.php
tests/unit/lib/utilTest.php
vendor-bin/behat/composer.json
vendor-bin/owncloud-codestyle/composer.json
vendor-bin/php_codesniffer/composer.json
vendor-bin/phpstan/composer.json

- update `.drone.star` code from activity app
- update tool dependencies
- update to coding-style 4.1

[tests-only] [full-ci] Update tool dependencies and drone CI code
